version: "3.8"

services:
  qrgen:
    image: milgradesec/qrgen:latest
    networks:
      - traefik_network
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.qrgen.entryPoints=https
        - traefik.http.routers.qrgen.rule=Host("api.paesa.es") && PathPrefix("/qr")
        - traefik.http.routers.qrgen.tls=true
        - traefik.http.routers.qrgen.service=qrgen-service
        - traefik.http.services.qrgen-service.loadbalancer.server.port=8080
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

networks:
  traefik_network:
    external: true
