name: Docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo GITCOMMIT=$(git describe --tags --always --abbrev=0 --dirty="-dev")

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build
        run: docker build . -f build.Dockerfile

      - name: Build and Push
        run: |
          docker buildx build -f build.Dockerfile --platform linux/amd64 . --tag milgradesec/qrgen:$GITCOMMIT --push
